minimumReleaseAge: 0
shamefullyHoist: true
strictPeerDependencies: false

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
  workerd: false

overrides:
  crossws: 0.4.12